import Nav from "@/components/nav/Nav";
import getWashsTypes from "@/requests/getWashsTypes";
import Head from "next/head";
import { useMemo } from "react";
import { create } from 'zustand';

export const useWashsTypesStore = create((set) => ({
  washsTypesList: [],
  setWashsTypesList: (newWashsTypesList) => set((state) => ({ washsTypesList: newWashsTypesList })),
}));

const Catalog = () => {
  const { washsTypesList, setWashsTypesList } = useWashsTypesStore();

  const GetWashsTypes = () => {
    getWashsTypes()
      .then((response) => setWashsTypesList(response.data));
  };

  useMemo(() => {
    GetWashsTypes();
  }, []);

  return (
    <>
      <Head>
        <title>Fast Clean | Nossos serviços</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous"></link>
      </Head>

      <Nav />

      <div className="container">
        <p>Desenvolver página sobre serviços da empresa ficctícia, sugestão: utilizar os cards do bootstrap</p>

        <div className="row">
          {washsTypesList && washsTypesList.map((washType) => {
            return (
              <div key={washType.wash_id} className="col-6">
                <div className="card">
                  <div className="card-body">
                    <span>
                      <h5 className="card-title">
                        {washType.name}
                      </h5>
                      <p className="card-text">
                        {washType.description}
                      </p>
                    </span>
                  </div>
                </div>
              </div>
            )
          })}
        </div>

      </div>
    </>
  );
};

export default Catalog;