import Head from 'next/head';
import Nav from '@/components/nav/Nav';
import helloaxios from '@/requests/example/helloaxios';

const Home = () => {
  const HandleSeeExample = () => {
    helloaxios()
      .then((response) => {
        console.log(response);
      });
  };

  return (
    <>
      <Head>
        <title>Fast Clean | Sobre nós</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous"></link>
      </Head>

      <Nav />

      <main>
        <div className="container">
          <p>Desenvolver página contando sobre a empresa ficctícia</p>

          <button className="btn btn-primary btn-sm" onClick={HandleSeeExample()}>Exemplo axios</button>
        </div>
      </main>
    </>
  );
};

export default Home;