import Head from "next/head";
import Link from "next/link";

const Navbar = () => {
  return (
    <>
      <Head>
        <title>Fast Clean | Sobre nós</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous"></link>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous" defer></script>
      </Head>
      
      <div className="container mt-2 mb-2">
        <ul className="nav nav-tabs justify-content-center">
          <li className="nav-item">
            <Link className="nav-link active" aria-current="page" href="/">Sobre nós</Link>
          </li>
          <li className="nav-item">
            <Link className="nav-link" aria-current="page" href="/catalog/Catalog">Nossos serviços</Link>
          </li>
          <li className="nav-item">
            <Link className="nav-link" aria-current="page" href="/schedule/Schedule">Agendar</Link>
          </li>
        </ul>
      </div>
    </>
  );
};

export default Navbar;