import Nav from "@/components/nav/Nav";
import Head from "next/head";

const Schedule = () => {
  return (
    <>
      <Head>
        <title>Fast Clean | Faça seu agendamento</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous"></link>
      </Head>

      <Nav />

      <div className="container">
        <p>Desenvolver página de agendamentos</p>
      </div>
    </>
  );
};

export default Schedule;